[package]
name = "youtube-tui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.4"
error-chain = "0.12.4"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3.15"
hyper = "0.14.9"
tokio-core = "0.1.18"
serde_json = "1.0.64"
youtube_dl = "0.6.1"